#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail


GENERATE_REPORT=1 MAIL_REPORT=0 rc=$(./app.py)

cp behave-report.html $(ARTIFACTS)

exit $rc

#end.
